export const locales = ["de", "fr", "es-419", "pt-BR", "ja"] as const;
export type Locale = (typeof locales)[number];

export const localeNames: Record<Locale, string> = {
  de: "Deutsch",
  fr: "Français",
  "es-419": "Español (LatAm)",
  "pt-BR": "Português (Brasil)",
  ja: "日本語",
};

export const messages = {
  de: {
    nav: ["Funktionen", "Preise", "Blog", "Über uns", "Download"],
    home: { eyebrow: "Katzengerechte Bildschirmzeit", title: "Mentales Wohlbefinden für deine Katze.", body: "Mibbles ist die iOS-App für Beschäftigung und Wohlbefinden von Katzen. Cat-TV, das ihre Aufmerksamkeit fesselt, Reaktionsvideos mit Cat Cam und Einblicke aus der Verhaltensforschung.", link: "So funktioniert’s", available: "Für iPhone und iPad · 7 Tage kostenlos testen", why: "Warum Mibbles", whyTitle: "Alles, was dem Indoor-Katzenalltag fehlt.", cards: [["Cat-TV", "Videos und Klänge für Katzen: Vögel, Fische, Beutebewegungen und beruhigende Szenen – abgestimmt auf die visuelle Wahrnehmung von Katzen."], ["Cat Cam", "Nimm die Reaktion deiner Katze während des Spiels auf und sieh sie anschließend neben dem Spielgeschehen. Cat Cam hält Spielmomente fest – sie ist keine Fernkamera."], ["Wohlbefinden", "Profile zeigen, was jede Katze gern spielt. Erhalte sanfte Empfehlungen für abwechslungsreiche Beschäftigung." ]], endTitle: "Jeden Tag ein bisschen mehr Spiel.", endBody: "Entdecke Spiele, die Katzen neugierig und in Bewegung halten." },
    features: { eyebrow: "Für ein glücklicheres Leben drinnen", title: "Ein glücklicherer Tag beginnt mit etwas zum Jagen.", body: "Mibbles macht den Bildschirm zu abwechslungsreicher Beschäftigung: neue Jagden, lebendige Bewegungen und Spiel, das mit jeder Runde persönlicher wird.", items: [["Spiel, das spannend bleibt", "Wähle aus Klassik, Käferjagd, Mäusejagd, Federjagd, Eidechsenjagd, Vogeljagd und mehr."], ["Spiel passend zu deiner Katze", "Passe Hintergrund, Textur, Dauer und Tempo an – oder lass Mibbles lernen, was deine Katze gern verfolgt."], ["Fortschritte, die du sehen kannst", "Mibbles merkt sich Spielrunden, tägliche Serien und Lieblingsspiele für jede Katze."], ["Reaktionen zum Wiederansehen", "Speichere Reaktionsclips, spiele sie erneut ab oder teile die schönen Momente." ]] },
    pricing: { eyebrow: "Mibbles Premium", title: "Sieben Tage voller schöner Spielmomente.", body: "Mehr Abwechslung, längere Spielrunden und Spiele, die lernen, was deine Katze neugierig macht.", annual: "Jährlich", monthly: "Monatlich", trial: "7 Tage kostenlos testen", annualPrice: "$29.99 USD/Jahr", monthlyPrice: "$2.99 USD/Monat", savings: "16 % sparen", details: "Die hier angezeigten Preise sind in USD. Nach dem Testzeitraum verlängert sich das gewählte Abo automatisch, bis du es kündigst. Den genauen lokalen Preis zeigt der App Store in der App an.", download: "Mibbles laden", free: "Alle Standard-Spielmodi bleiben kostenlos." },
    about: { eyebrow: "Über Mibbles", title: "Mibbles begann mit einer gelangweilten Katze namens Suki.", intro: "Mibbles begann in einer kleinen Wohnung mit Suki. Ihre Menschen arbeiteten lange, und für Beschäftigung blieb oft nur ein Spielzeug, für das ihnen die Energie fehlte. Es musste einen besseren Weg geben.", mission: "Unsere Mission", missionBody: "Wohnungskatzen brauchen anregende Umgebungen. Die Forschung zum Wohlbefinden von Katzen zeigt, wie wichtig Beschäftigung ist. Wir machen diese Erkenntnisse zu etwas, das Katzenmenschen im Alltag leicht nutzen können.", team: "Unser Team", teamTitle: "Ein kleines Team von Katzenfans", teamBody: "Mibbles entsteht in Florida – aus unserer Begeisterung für Tiere und unserer Erfahrung in Wirtschaft und Gesundheitswesen. Wir arbeiten jeden Tag daran, die App für Katzen noch anregender zu machen.", contact: "Schreib uns", end: "Hilf uns, jeder Wohnungskatze einen besseren Tag zu schenken." },
    download: { eyebrow: "Mibbles herunterladen", title: "Der neue Lieblingsbildschirm deiner Katze.", body: "Interaktives Spielen und mentale Beschäftigung – für Katzen gemacht.", loved: "Geliebt von Katzen und ihren Menschen", tiktok: "Du bist gerade auf TikTok!", explain: "TikTok öffnet App-Store-Links nicht direkt. In wenigen Schritten kannst du Mibbles trotzdem laden.", step1: "Tippe auf das Menü ··· oben rechts.", step2: "Wähle „Im Browser öffnen“.", step3: "Tippe unten, um Mibbles im App Store zu laden.", open: "Im Browser öffnen", copy: "Link kopieren", cta: "Im App Store laden", secure: "Sicher und offiziell · App-Store-Link" },
    common: { learn: "Mehr erfahren", home: "Startseite", language: "Sprache" },
  },
  fr: {
    nav: ["Fonctionnalités", "Tarifs", "Blog", "À propos", "Télécharger"],
    home: { eyebrow: "Des écrans adaptés aux chats", title: "Le bien-être mental de votre chat.", body: "Mibbles est l’app iOS dédiée aux jeux et au bien-être des chats : des vidéos qui captent leur attention, des replays de leurs réactions avec Cat Cam et des conseils inspirés de la recherche comportementale.", link: "Comment ça marche", available: "Sur iPhone et iPad · Essai gratuit de 7 jours", why: "Pourquoi Mibbles", whyTitle: "Tout ce qui manque au quotidien d’un chat d’intérieur.", cards: [["Cat TV", "Des vidéos et des sons pensés pour les chats : oiseaux, poissons, mouvements de proies et scènes apaisantes, adaptés à leur attention visuelle."], ["Cat Cam", "Filmez la réaction de votre chat pendant une partie, puis revivez-la à côté du jeu. Cat Cam capture les moments de jeu ; ce n’est pas une caméra à distance."], ["Bien-être", "Des profils révèlent les jeux préférés de chaque chat. Recevez des conseils simples pour varier ses activités."]], endTitle: "Un peu plus de jeu, chaque jour.", endBody: "Découvrez des jeux qui éveillent la curiosité et font bouger les chats." },
    features: { eyebrow: "Pour des chats d’intérieur épanouis", title: "Une journée plus heureuse commence par une proie à poursuivre.", body: "Mibbles transforme l’écran en activité stimulante : de nouvelles chasses, des mouvements réactifs et des jeux qui s’adaptent à chaque partie.", items: [["Des jeux toujours captivants", "Choisissez parmi Classique, Chasse au scarabée, Souris, Plume, Lézard, Oiseau et bien plus."], ["Un jeu adapté à votre chat", "Choisissez le fond, la texture, la durée et la vitesse, ou laissez Mibbles apprendre ce qui l’intéresse."], ["Des progrès visibles", "Mibbles mémorise les parties, les séries quotidiennes et les jeux favoris de chaque chat."], ["Des réactions à garder", "Enregistrez les réactions, revoyez les clips et partagez les meilleurs moments."]] },
    pricing: { eyebrow: "Mibbles Premium", title: "Sept jours de jeu plus heureux.", body: "Plus de variété, des sessions plus longues et des jeux qui apprennent ce qui rend votre chat curieux.", annual: "Annuel", monthly: "Mensuel", trial: "Essai gratuit de 7 jours", annualPrice: "$29.99 USD/an", monthlyPrice: "$2.99 USD/mois", savings: "16 % d’économie", details: "Les prix affichés ici sont en USD. Après l’essai, l’abonnement choisi se renouvelle automatiquement jusqu’à résiliation. L’App Store indique le prix local exact dans l’app.", download: "Télécharger Mibbles", free: "Tous les modes de jeu standard restent gratuits." },
    about: { eyebrow: "À propos de Mibbles", title: "Mibbles est né avec Suki, une chatte qui s’ennuyait.", intro: "Mibbles a commencé dans un petit appartement avec Suki. Ses humains travaillaient de longues journées et n’avaient pas toujours l’énergie de sortir la canne à pêche. Il devait exister une meilleure solution.", mission: "Notre mission", missionBody: "Les chats d’intérieur ont besoin d’un environnement stimulant. Les recherches sur leur bien-être soulignent l’importance de l’enrichissement. Nous rendons ces connaissances faciles à intégrer au quotidien.", team: "Notre équipe", teamTitle: "Une petite équipe de passionnés de chats", teamBody: "Mibbles est développé en Floride, avec notre passion pour les animaux et notre expérience en entreprise et en santé. Chaque jour, nous améliorons l’app pour stimuler davantage les chats.", contact: "Nous contacter", end: "Aidons chaque chat d’intérieur à passer une meilleure journée." },
    download: { eyebrow: "Télécharger Mibbles", title: "Le nouvel écran préféré de votre chat.", body: "Des jeux interactifs et une stimulation mentale conçus pour les chats.", loved: "Adopté par les chats et leurs humains", tiktok: "Vous êtes sur TikTok !", explain: "TikTok n’ouvre pas directement les liens de l’App Store. Quelques étapes suffisent pour télécharger Mibbles.", step1: "Touchez le menu ··· en haut à droite.", step2: "Choisissez « Ouvrir dans le navigateur ». ", step3: "Touchez le bouton ci-dessous pour télécharger Mibbles sur l’App Store.", open: "Ouvrir dans le navigateur", copy: "Copier le lien", cta: "Télécharger sur l’App Store", secure: "Officiel et sécurisé · Lien App Store" },
    common: { learn: "En savoir plus", home: "Accueil", language: "Langue" },
  },
  "es-419": {
    nav: ["Funciones", "Precios", "Blog", "Nosotros", "Descargar"],
    home: { eyebrow: "Tiempo de pantalla pensado para gatos", title: "Bienestar mental para tu gato.", body: "Mibbles es la app de iOS para el entretenimiento y bienestar de los gatos: videos que captan su atención, repeticiones de sus reacciones con Cat Cam e información basada en estudios de comportamiento felino.", link: "Cómo funciona", available: "Para iPhone y iPad · Prueba gratis por 7 días", why: "Por qué Mibbles", whyTitle: "Lo que le falta al día a día de un gato de interior.", cards: [["Cat TV", "Videos y sonidos para gatos: aves, peces, movimientos de presas y escenas tranquilas, diseñados para su atención visual."], ["Cat Cam", "Graba la reacción de tu gato mientras juega y vuelve a verla junto a la acción en pantalla. Cat Cam captura momentos de juego; no es una cámara remota."], ["Bienestar", "Los perfiles muestran qué juegos disfruta cada gato. Recibe recomendaciones sencillas para variar sus actividades."]], endTitle: "Un poco más de juego cada día.", endBody: "Descubre juegos que despiertan la curiosidad y ponen a los gatos en movimiento." },
    features: { eyebrow: "Para gatos de interior más felices", title: "Un día más feliz empieza con algo que perseguir.", body: "Mibbles convierte la pantalla en entretenimiento activo: nuevas presas, movimientos reactivos y juegos más personalizados en cada sesión.", items: [["Juegos que siguen siendo interesantes", "Elige entre Clásico, Persecución de escarabajos, Ratón, Plumas, Lagartija, Aves y más."], ["Juego pensado para tu gato", "Elige fondo, textura, duración y velocidad, o deja que Mibbles aprenda qué le gusta perseguir."], ["Progreso que puedes ver", "Mibbles registra sesiones, rachas diarias y juegos favoritos de cada gato."], ["Reacciones para guardar", "Guarda las reacciones, vuelve a ver los clips y comparte esos momentos especiales."]] },
    pricing: { eyebrow: "Mibbles Premium", title: "Siete días de juego más feliz.", body: "Más variedad, sesiones más largas y juegos que aprenden qué despierta la curiosidad de tu gato.", annual: "Anual", monthly: "Mensual", trial: "Prueba gratis por 7 días", annualPrice: "$29.99 USD/año", monthlyPrice: "$2.99 USD/mes", savings: "Ahorra 16 %", details: "Los precios que aparecen aquí están en USD. Al terminar la prueba, el plan elegido se renueva automáticamente hasta que lo canceles. La App Store muestra el precio local exacto en la app.", download: "Descargar Mibbles", free: "Todos los modos de juego estándar siguen siendo gratis." },
    about: { eyebrow: "Acerca de Mibbles", title: "Mibbles nació con Suki, una gata aburrida.", intro: "Mibbles comenzó en un departamento pequeño con Suki. Sus humanos trabajaban muchas horas y, al final del día, a veces no tenían energía para jugar con una varita. Tenía que haber una mejor opción.", mission: "Nuestra misión", missionBody: "Los gatos de interior necesitan entornos estimulantes. La investigación sobre su bienestar destaca la importancia del enriquecimiento. Queremos que estos conocimientos sean fáciles de usar todos los días.", team: "Nuestro equipo", teamTitle: "Un pequeño equipo de amantes de los gatos", teamBody: "Mibbles se desarrolla en Florida, con pasión por los animales y experiencia en negocios y salud. Trabajamos cada día para que la app estimule más a los gatos.", contact: "Contáctanos", end: "Ayúdanos a darles un mejor día a los gatos de interior." },
    download: { eyebrow: "Descarga Mibbles", title: "La nueva pantalla favorita de tu gato.", body: "Juego interactivo y estimulación mental, diseñados para gatos.", loved: "Les encanta a los gatos y a sus familias", tiktok: "¡Estás en TikTok!", explain: "TikTok no permite abrir directamente los enlaces de App Store. Puedes descargar Mibbles en unos pasos.", step1: "Toca el menú ··· en la esquina superior derecha.", step2: "Selecciona “Abrir en el navegador”.", step3: "Toca el botón de abajo para descargar Mibbles en App Store.", open: "Abrir en el navegador", copy: "Copiar enlace", cta: "Descargar en App Store", secure: "Seguro y oficial · Enlace de App Store" },
    common: { learn: "Conoce más", home: "Inicio", language: "Idioma" },
  },
  "pt-BR": {
    nav: ["Recursos", "Preços", "Blog", "Sobre", "Baixar"],
    home: { eyebrow: "Tempo de tela feito para gatos", title: "Bem-estar mental para o seu gato.", body: "Mibbles é o app para iOS de brincadeiras e bem-estar felino: vídeos que prendem a atenção, replays das reações com Cat Cam e dicas inspiradas em pesquisas sobre comportamento dos gatos.", link: "Como funciona", available: "Para iPhone e iPad · 7 dias de teste grátis", why: "Por que Mibbles", whyTitle: "Tudo o que falta na rotina de um gato que vive dentro de casa.", cards: [["Cat TV", "Vídeos e sons para gatos: pássaros, peixes, movimentos de presas e cenas tranquilas, pensados para a atenção visual deles."], ["Cat Cam", "Grave a reação do seu gato durante uma brincadeira e reveja ao lado da ação na tela. Cat Cam registra momentos de diversão; não é uma câmera remota."], ["Bem-estar", "Os perfis mostram as brincadeiras favoritas de cada gato. Receba sugestões simples para variar as atividades."]], endTitle: "Um pouco mais de brincadeira todo dia.", endBody: "Descubra jogos que despertam a curiosidade e deixam os gatos em movimento." },
    features: { eyebrow: "Para gatos de dentro de casa mais felizes", title: "Um dia mais feliz começa com algo para perseguir.", body: "Mibbles transforma a tela em enriquecimento ativo: novas caçadas, movimentos responsivos e brincadeiras mais personalizadas a cada sessão.", items: [["Brincadeiras sempre interessantes", "Escolha entre Clássico, Caça ao Besouro, Ratinho, Penas, Lagarto, Pássaros e muito mais."], ["Brincadeiras do jeito do seu gato", "Escolha o fundo, a textura, a duração e a velocidade, ou deixe o Mibbles aprender o que desperta o interesse dele."], ["Progresso que você percebe", "O Mibbles registra sessões, sequências diárias e jogos favoritos de cada gato."], ["Reações para guardar", "Salve as reações, reveja os clipes e compartilhe os momentos especiais."]] },
    pricing: { eyebrow: "Mibbles Premium", title: "Sete dias de brincadeiras mais felizes.", body: "Mais variedade, sessões mais longas e jogos que aprendem o que deixa seu gato curioso.", annual: "Anual", monthly: "Mensal", trial: "7 dias de teste grátis", annualPrice: "$29.99 USD/ano", monthlyPrice: "$2.99 USD/mês", savings: "Economize 16%", details: "Os preços exibidos aqui estão em USD. Após o teste, a assinatura escolhida será renovada automaticamente até ser cancelada. O preço local exato aparece no app pela App Store.", download: "Baixar Mibbles", free: "Todos os modos de jogo padrão continuam grátis." },
    about: { eyebrow: "Sobre o Mibbles", title: "O Mibbles começou com uma gata entediada chamada Suki.", intro: "O Mibbles começou em um apartamento pequeno com a Suki. Seus humanos trabalhavam muitas horas e nem sempre tinham energia para brincar com uma varinha. Precisava existir um jeito melhor.", mission: "Nossa missão", missionBody: "Gatos que vivem dentro de casa precisam de ambientes estimulantes. Pesquisas sobre o bem-estar felino mostram a importância do enriquecimento. Queremos transformar esse conhecimento em algo fácil de usar no dia a dia.", team: "Nossa equipe", teamTitle: "Uma equipe pequena de apaixonados por gatos", teamBody: "O Mibbles é feito na Flórida por pessoas que amam animais e têm experiência em negócios e saúde. Trabalhamos todos os dias para deixar o app ainda mais estimulante para os gatos.", contact: "Fale com a gente", end: "Ajude a tornar melhor o dia de cada gato que vive dentro de casa." },
    download: { eyebrow: "Baixe o Mibbles", title: "A nova tela favorita do seu gato.", body: "Brincadeiras interativas e estímulo mental feitos para gatos.", loved: "Adorado por gatos e suas pessoas", tiktok: "Você está no TikTok!", explain: "O TikTok não abre links da App Store diretamente. Mas você pode baixar o Mibbles em poucos passos.", step1: "Toque no menu ··· no canto superior direito.", step2: "Selecione “Abrir no navegador”.", step3: "Toque no botão abaixo para baixar o Mibbles na App Store.", open: "Abrir no navegador", copy: "Copiar link", cta: "Baixar na App Store", secure: "Seguro e oficial · Link da App Store" },
    common: { learn: "Saiba mais", home: "Início", language: "Idioma" },
  },
  ja: {
    nav: ["機能", "料金", "ブログ", "Mibblesについて", "ダウンロード"],
    home: { eyebrow: "猫のためのスクリーン時間", title: "愛猫の心の健康をサポート。", body: "Mibblesは、猫の遊びとウェルネスのためのiOSアプリです。夢中になれる猫向け動画、Cat Camでのリアクション再生、猫の行動研究に基づくヒントをお届けします。", link: "使い方を見る", available: "iPhone・iPad対応 · 7日間無料トライアル", why: "Mibblesが選ばれる理由", whyTitle: "室内猫の毎日に足りないものを。", cards: [["Cat TV", "鳥や魚、獲物の動き、落ち着いた映像と音。猫の視覚的な興味に合わせて作られています。"], ["Cat Cam", "ゲーム中の愛猫の反応を撮影し、画面の動きと並べて再生できます。Cat Camは遊びの記録用で、遠隔カメラではありません。"], ["ウェルネス", "猫ごとのプロフィールで好きな遊びを記録。毎日の遊びに取り入れやすい提案を受け取れます。"]], endTitle: "毎日に、もう少し遊びを。", endBody: "好奇心を刺激し、体を動かすゲームを見つけましょう。" },
    features: { eyebrow: "室内猫にもっと楽しい毎日を", title: "追いかけたくなる遊びで、もっと楽しい一日を。", body: "Mibblesは画面をアクティブな遊び場に。新しいハント、反応のある動き、遊ぶたびに猫に合わせた体験を楽しめます。", items: [["飽きないゲーム", "クラシック、ビートルチェイス、マウス、フェザー、リザード、バードなどから選べます。"], ["愛猫に合わせた遊び", "背景、質感、時間、速さを選ぶか、Mibblesに好みを学習させましょう。"], ["遊びの記録を確認", "猫ごとのプレイ時間、連続記録、お気に入りゲームを保存します。"], ["リアクションを保存", "遊びのリアクションを保存して、再生や共有ができます。"]] },
    pricing: { eyebrow: "Mibbles Premium", title: "遊びが広がる7日間。", body: "もっと多彩な遊び、長いセッション、愛猫の好みに合わせて学ぶゲームを。", annual: "年額", monthly: "月額", trial: "7日間無料トライアル", annualPrice: "$29.99 USD／年", monthlyPrice: "$2.99 USD／月", savings: "16%お得", details: "ここに表示されている価格はUSDです。トライアル終了後、解約するまで選択したプランが自動更新されます。正確な現地価格はアプリ内でApp Storeに表示されます。", download: "Mibblesをダウンロード", free: "標準ゲームモードはすべて無料です。" },
    about: { eyebrow: "Mibblesについて", title: "退屈していた猫、スキがMibblesの始まりでした。", intro: "小さなアパートで、退屈そうな猫のスキと暮らす日々からMibblesは始まりました。飼い主は長時間働き、疲れて猫じゃらしで遊ぶ余裕がない日もありました。もっと良い方法があるはずでした。", mission: "私たちの使命", missionBody: "室内で暮らす猫には、刺激のある環境が必要です。猫のウェルネス研究でも、環境を豊かにすることの大切さが示されています。その知識を毎日の暮らしで使いやすくすることが私たちの目標です。", team: "チーム", teamTitle: "猫を愛する小さなチーム", teamBody: "Mibblesはフロリダを拠点に、動物への愛情とビジネス・ヘルスケアの経験を持つチームが開発しています。猫にとってより楽しいアプリを目指して、日々改善を続けています。", contact: "お問い合わせ", end: "室内で暮らすすべての猫に、もっと楽しい一日を。" },
    download: { eyebrow: "Mibblesをダウンロード", title: "愛猫のお気に入りの新しい画面。", body: "猫のために作られた、インタラクティブな遊びと知的刺激。", loved: "猫と飼い主に選ばれています", tiktok: "TikTokからご覧の方へ", explain: "TikTokではApp Storeへのリンクを直接開けません。次の手順でMibblesをダウンロードできます。", step1: "右上の···メニューをタップします。", step2: "「ブラウザで開く」を選びます。", step3: "下のボタンをタップしてApp Storeからダウンロードします。", open: "ブラウザで開く", copy: "リンクをコピー", cta: "App Storeからダウンロード", secure: "安全・公式 · App Storeリンク" },
    common: { learn: "詳しく見る", home: "ホーム", language: "言語" },
  },
} as const;

export type Messages = (typeof messages)[Locale];

export function isLocale(value: string): value is Locale {
  return (locales as readonly string[]).includes(value);
}

export function localizedMetadata(localeValue: string, page: "home" | "features" | "pricing" | "about" | "download" | "downloads") {
  if (!isLocale(localeValue)) return {};
  const copy = messages[localeValue];
  const segment = page === "home" ? "" : `/${page}`;
  const title = page === "home" ? copy.home.title : page === "features" ? copy.nav[0] : page === "pricing" ? copy.nav[1] : page === "about" ? copy.nav[3] : copy.download.eyebrow;
  const description = page === "features" ? copy.features.body : page === "pricing" ? copy.pricing.body : page === "about" ? copy.about.intro : page === "home" ? copy.home.body : copy.download.body;
  const baseUrl = "https://mibbles.app";
  return {
    title: `${title} — Mibbles`,
    description,
    alternates: {
      canonical: `${baseUrl}/${localeValue}${segment}`,
      languages: Object.fromEntries(locales.map((locale) => [locale, `${baseUrl}/${locale}${segment}`])),
    },
    openGraph: { title: `${title} — Mibbles`, description },
  };
}
